format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "nord"

[directory]
style = 'bold blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
style = 'green'
symbol = 'git:'
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'red'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'cyan'
symbol = 'py:'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
format = '[$symbol($version )]($style)'
symbol = 'lua:'

[nodejs]
style = 'blue'
symbol = 'node:'

[golang]
style = 'blue'
symbol = 'go:'

[haskell]
style = 'blue'
symbol = 'hs:'

[rust]
style = 'yellow'
symbol = 'rs:'

[ruby]
style = 'blue'
symbol = 'rb:'

[aws]
symbol = 'aws:'
style = 'yellow'
format = '[$symbol($profile )(\[$region\] )(\[$duration\] )]($style)'

[docker_context]
symbol = 'docker:'
style = 'blue'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = 'jobs:'
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'gray'
format = '[$duration]($style)'

[character]
success_symbol = '[>](green)'
error_symbol = '[>](red)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
cyan = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.onedark]
dark_blue='#61afef'
blue='#56b6c2'
red='#e06c75'
green='#98c379'
purple='#c678dd'
cyan='#56b6c2'
orange='#be5046'
yellow='#e5c07b'
gray='#828997'
white ='#abb2bf'
black='#2c323c'
